/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package igv_tester;
//import java.awt.Toolkit;
import com.sun.glass.events.KeyEvent;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.text.DefaultCaret;
/**
 *
 * @author Juan Antonio Martinez Castellanos - U375716
 */
public class IGV_UI extends javax.swing.JFrame {
    //This class is the main UI
    
    
    private static String badge;
    
    public IGV_UI() {
        badge = "empty";
        initComponents();
        textField1.setVisible(false);
        badgeField.setVisible(false);
        functionalField.setVisible(false);
        dialogReturn = -1;
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setExtendedState(getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        //Always at auto scroll to the bottom of the text field
        DefaultCaret caret1 = (DefaultCaret)textField1.getCaret();
        caret1.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        DefaultCaret caret2 = (DefaultCaret)functionalField.getCaret();
        caret2.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }
    
    //This is the dialog box with 2 options, used many times
    public void infoBox(String infoMessage, String titleBar, Object[] options) {
        //I had to implement my own buttons with my own AbstractAction
        //so that we could use the barcode scanner to select the buttons
        JButton b0 = new JButton((String)options[0]);
        JButton b1 = new JButton((String)options[1]);
        AbstractAction aa = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent event) {
                if(event.getSource() == b0)
                    dialogReturn = 0;
                else if(event.getSource() == b1)
                    dialogReturn = 1;
                try{Thread.sleep(500);} catch(Exception f){}
                IGV_Tester.dialogLatch.countDown();
                JOptionPane.getRootFrame().dispose();
            }
        };
        b0.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK), "LEFT");
        b0.getActionMap().put("LEFT", aa);
        b0.addActionListener(aa);
        b1.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK), "RIGHT");
        b1.getActionMap().put("RIGHT", aa);
        b1.addActionListener(aa);
        options[0] = b0;
        options[1] = b1;
        JOptionPane.showOptionDialog(null, infoMessage,
                "InfoBox: "+titleBar, JOptionPane.YES_NO_OPTION,
                JOptionPane.ERROR_MESSAGE, null, options, options[1]);
        
    }
    
    //This is a dialog box with 1 option.
    //Used only once, for the motor installation.
    public void motorReminder() {
        JOptionPane p = new JOptionPane();
        JOptionPane.showOptionDialog(null, "Please, install the motor now!",
                "Installing motor", JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE, null,
                new String[] {"DONE!"}, "DONE!");
    }
    
    public int getDialogReturn() {
        int temp = dialogReturn;
        dialogReturn = -1;
        return temp;
    }
    
    public static void rundisplay(IGV_UI gui){
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gui.setVisible(true);
            }
        });
    }
    
    //Method to print to the torque box.
    public void setOutputDC(String output){
        String temp = textField1.getText();
        textField1.setText(temp+output);
    }
    
    //Method to print to the functional box.
    public void setOutputFunctional(String output){
        String temp = functionalField.getText();
        functionalField.setText(temp+output);
    }
    
    public static String getBadge() {
        return badge;
    }
    
    public void startTorque() {
        textField1.setVisible(true);
        textField1.requestFocus();
        label3.setText("Torque Validation");
    }
    
    public void startBadge() {
        badgeField.setVisible(true);
        badgeField.requestFocus();
        badgeLabel.setText("Scan badge to proceed to functional testing");
    }
    
    public void startFunctional() {
        functionalField.setVisible(true);
        functionalLabel.setText("Functional testing");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        functionalLabel = new java.awt.Label();
        label3 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        textField1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        badgeField = new javax.swing.JTextArea();
        badgeLabel = new java.awt.Label();
        jScrollPane4 = new javax.swing.JScrollPane();
        functionalField = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(0, 0));

        label1.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        label1.setText("IGV Tester");

        functionalLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        label3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        textField1.setEditable(false);
        textField1.setColumns(20);
        textField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textField1.setRows(5);
        jScrollPane2.setViewportView(textField1);

        badgeField.setColumns(20);
        badgeField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        badgeField.setRows(1);
        badgeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                badgeFieldKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(badgeField);

        badgeLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        functionalField.setEditable(false);
        functionalField.setColumns(20);
        functionalField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        functionalField.setRows(5);
        jScrollPane4.setViewportView(functionalField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(badgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1521, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1582, Short.MAX_VALUE)
                            .addComponent(functionalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1549, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 1583, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(751, 751, 751)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(badgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(functionalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void badgeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_badgeFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar() == '\n'){
            badge = badgeField.getText();
            badgeField.setEditable(false);
        }
    }//GEN-LAST:event_badgeFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IGV_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IGV_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IGV_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IGV_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new IGV_UI().setVisible(true);
            }
        });
    }

    private static int dialogReturn;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea badgeField;
    private java.awt.Label badgeLabel;
    private javax.swing.JTextArea functionalField;
    private java.awt.Label functionalLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private javax.swing.JTextArea textField1;
    // End of variables declaration//GEN-END:variables
}
